version: "3.1"
services:
  apache:
    image: ulsmith/alpine-apache-php7
    environment:
      - MYSQL_HOST=db
      - APACHE_SERVER_NAME=apache.docker.localhost
      - PHP_SHORT_OPEN_TAG=On
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_HTML_ERRORS=On
      - PHP_XDEBUG_ENABLED=true
    volumes:
      - ./:/app
    ports: 
      - 8080:80
    cap_add:
      - SYS_TIME
      - SYS_NICE
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080